; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+zbb,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Counting the bits of a wide value has no generic expansion at this width, so each
; of the three gets an instruction whose result is an XLen value.

declare i256 @llvm.ctpop.i256(i256)
declare i256 @llvm.ctlz.i256(i256, i1)
declare i256 @llvm.cttz.i256(i256, i1)

define i256 @ctpop_i256(i256 %a) {
; CHECK-LABEL: ctpop_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wcpop a0, w0
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  %r = call i256 @llvm.ctpop.i256(i256 %a)
  ret i256 %r
}

define i256 @ctlz_i256(i256 %a) {
; CHECK-LABEL: ctlz_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wclz a0, w0
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  %r = call i256 @llvm.ctlz.i256(i256 %a, i1 false)
  ret i256 %r
}

define i256 @ctlz_zero_undef_i256(i256 %a) {
; CHECK-LABEL: ctlz_zero_undef_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wclz a0, w0
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  %r = call i256 @llvm.ctlz.i256(i256 %a, i1 true)
  ret i256 %r
}

define i256 @cttz_i256(i256 %a) {
; CHECK-LABEL: cttz_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wctz a0, w0
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  %r = call i256 @llvm.cttz.i256(i256 %a, i1 false)
  ret i256 %r
}

define i64 @ctpop_truncated(i256 %a) {
; CHECK-LABEL: ctpop_truncated:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wcpop a0, w0
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    revive.wtrunc a0, w0
; CHECK-NEXT:    ret
  %r = call i256 @llvm.ctpop.i256(i256 %a)
  %t = trunc i256 %r to i64
  ret i64 %t
}
