; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; The per-width argument register lists overlap -- V8M8 covers v8-v15, aliasing
; V8M2 and V8M4 -- so allocation has to see the aliasing or two arguments land on
; top of each other. Each test stores its arguments to expose the assignment.

define void @i256_then_i1024(i256 %a, i1024 %b, ptr %p) {
; CHECK-LABEL: i256_then_i1024:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wst v8, 0(a0)
; CHECK-NEXT:    vsetivli zero, 16, e64, m8, ta, ma
; CHECK-NEXT:    revive.wst v16, 0(a0)
; CHECK-NEXT:    ret
  store volatile i256 %a, ptr %p
  store volatile i1024 %b, ptr %p
  ret void
}

define void @i1024_then_i256(i1024 %a, i256 %b, ptr %p) {
; CHECK-LABEL: i1024_then_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e64, m8, ta, ma
; CHECK-NEXT:    revive.wst v8, 0(a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wst v16, 0(a0)
; CHECK-NEXT:    ret
  store volatile i1024 %a, ptr %p
  store volatile i256 %b, ptr %p
  ret void
}

define void @all_three_widths(i1024 %a, i256 %b, i512 %c, ptr %p) {
; CHECK-LABEL: all_three_widths:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e64, m8, ta, ma
; CHECK-NEXT:    revive.wst v8, 0(a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wst v16, 0(a0)
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    revive.wst v20, 0(a0)
; CHECK-NEXT:    ret
  store volatile i1024 %a, ptr %p
  store volatile i256 %b, ptr %p
  store volatile i512 %c, ptr %p
  ret void
}

; Eight i256 arguments fill v8m2..v22m2; the ninth is passed by memory.
define void @i256_exhaust(i256 %a, i256 %b, i256 %c, i256 %d, i256 %e, i256 %f,
; CHECK-LABEL: i256_exhaust:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    addi s0, sp, 32
; CHECK-NEXT:    .cfi_def_cfa s0, 0
; CHECK-NEXT:    andi sp, sp, -32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wld v10, 0(s0)
; CHECK-NEXT:    revive.wst v8, 0(a0)
; CHECK-NEXT:    revive.wst v10, 0(a0)
; CHECK-NEXT:    addi sp, s0, -32
; CHECK-NEXT:    .cfi_def_cfa sp, 32
; CHECK-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
                          i256 %g, i256 %h, i256 %i, ptr %p) {
  store volatile i256 %a, ptr %p
  store volatile i256 %i, ptr %p
  ret void
}

; Only two LMUL=8 argument registers exist, so the third is passed by memory.
define void @i1024_exhaust(i1024 %a, i1024 %b, i1024 %c, ptr %p) {
; CHECK-LABEL: i1024_exhaust:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    addi s0, sp, 32
; CHECK-NEXT:    .cfi_def_cfa s0, 0
; CHECK-NEXT:    andi sp, sp, -32
; CHECK-NEXT:    vsetivli zero, 16, e64, m8, ta, ma
; CHECK-NEXT:    revive.wld v16, 0(s0)
; CHECK-NEXT:    revive.wst v8, 0(a0)
; CHECK-NEXT:    revive.wst v16, 0(a0)
; CHECK-NEXT:    addi sp, s0, -32
; CHECK-NEXT:    .cfi_def_cfa sp, 32
; CHECK-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  store volatile i1024 %a, ptr %p
  store volatile i1024 %c, ptr %p
  ret void
}

; Wide returns come back in registers, not through a hidden pointer.
declare i512 @callee512(i512, i512)

define i512 @call_512(i512 %a, i512 %b) {
; CHECK-LABEL: call_512:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv4r.v v16, v8
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vmv4r.v v12, v16
; CHECK-NEXT:    call callee512
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %r = call i512 @callee512(i512 %b, i512 %a)
  ret i512 %r
}

declare i1024 @callee1024(i1024, i1024)

define i1024 @call_1024(i1024 %a, i1024 %b) {
; CHECK-LABEL: call_1024:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv8r.v v24, v8
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vmv8r.v v16, v24
; CHECK-NEXT:    call callee1024
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %r = call i1024 @callee1024(i1024 %b, i1024 %a)
  ret i1024 %r
}

; The two register files are allocated independently, so the pointer is in a0.
define void @wide_and_gpr(i64 %x, i512 %a, i64 %y, ptr %p) {
; CHECK-LABEL: wide_and_gpr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    revive.wst v8, 0(a2)
; CHECK-NEXT:    sd a1, 0(a2)
; CHECK-NEXT:    ret
  store volatile i64 %x, ptr %p
  store volatile i512 %a, ptr %p
  store volatile i64 %y, ptr %p
  ret void
}

; With VLEN pinned a spill slot is a fixed size at an immediate offset.
declare void @clobber()

define i1024 @spill_1024(i1024 %a) {
; CHECK-LABEL: spill_1024:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -144
; CHECK-NEXT:    .cfi_def_cfa_offset 144
; CHECK-NEXT:    sd ra, 136(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    addi a0, sp, 8
; CHECK-NEXT:    vs8r.v v8, (a0) # 128-byte Folded Spill
; CHECK-NEXT:    call clobber
; CHECK-NEXT:    addi a0, sp, 8
; CHECK-NEXT:    vl8r.v v8, (a0) # 128-byte Folded Reload
; CHECK-NEXT:    ld ra, 136(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 144
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  call void @clobber()
  ret i1024 %a
}

define i512 @spill_512(i512 %a) {
; CHECK-LABEL: spill_512:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -80
; CHECK-NEXT:    .cfi_def_cfa_offset 80
; CHECK-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    addi a0, sp, 8
; CHECK-NEXT:    vs4r.v v8, (a0) # 64-byte Folded Spill
; CHECK-NEXT:    call clobber
; CHECK-NEXT:    addi a0, sp, 8
; CHECK-NEXT:    vl4r.v v8, (a0) # 64-byte Folded Reload
; CHECK-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 80
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  call void @clobber()
  ret i512 %a
}
