; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec,+unaligned-scalar-mem \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; A local frame past 2 KB puts its objects out of reach of the stack pointer, so
; the local stack slot allocation pass materializes one base register per block
; and reuses it, writing each object's distance from that base straight into the
; instruction's immediate. Nothing on that path rounds the value or asks the
; instruction what it can hold, and a byte-aligned object beside a 32-aligned one
; puts an odd distance there.
;
; The immediate is where the memory forms used to keep their width, so an odd one
; silently halved the access: the words these two functions now emit for offset 1
; are the words the old encoding emitted for the 128-bit load and store at offset
; 0. The width is funct3 now, so an odd offset is only an offset.

declare void @escape(ptr)

define void @odd_base_offset_store(i256 %v) {
; CHECK-LABEL: odd_base_offset_store:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -2032
; CHECK-NEXT:    .cfi_def_cfa_offset 2032
; CHECK-NEXT:    sd ra, 2024(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 2016(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    addi s0, sp, 2032
; CHECK-NEXT:    .cfi_def_cfa s0, 0
; CHECK-NEXT:    addi sp, sp, -2048
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    andi sp, sp, -32
; CHECK-NEXT:    addi a0, sp, 2047
; CHECK-NEXT:    addi a0, a0, 1984
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    revive.wst v8, 1(a0)
; CHECK-NEXT:    sb a1, 0(a0)
; CHECK-NEXT:    addi a0, sp, 31
; CHECK-NEXT:    call escape
; CHECK-NEXT:    addi sp, s0, -2032
; CHECK-NEXT:    .cfi_def_cfa sp, 2032
; CHECK-NEXT:    ld ra, 2024(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 2016(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    addi sp, sp, 2032
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %obj = alloca i256, align 32
  %byte = alloca i8, align 1
  %big = alloca [4000 x i8], align 1
  store i256 %v, ptr %obj, align 1
  store i8 7, ptr %byte, align 1
  call void @escape(ptr %big)
  ret void
}

define i256 @odd_base_offset_load() {
; CHECK-LABEL: odd_base_offset_load:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -2032
; CHECK-NEXT:    .cfi_def_cfa_offset 2032
; CHECK-NEXT:    sd ra, 2024(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 2016(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 2008(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    .cfi_offset s1, -24
; CHECK-NEXT:    addi s0, sp, 2032
; CHECK-NEXT:    .cfi_def_cfa s0, 0
; CHECK-NEXT:    addi sp, sp, -2048
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    andi sp, sp, -32
; CHECK-NEXT:    addi s1, sp, 2047
; CHECK-NEXT:    addi s1, s1, 1984
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    sb a0, 0(s1)
; CHECK-NEXT:    addi a0, sp, 31
; CHECK-NEXT:    call escape
; CHECK-NEXT:    revive.wld v8, 1(s1)
; CHECK-NEXT:    addi sp, s0, -2032
; CHECK-NEXT:    .cfi_def_cfa sp, 2032
; CHECK-NEXT:    ld ra, 2024(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 2016(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 2008(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 2032
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %obj = alloca i256, align 32
  %byte = alloca i8, align 1
  %big = alloca [4000 x i8], align 1
  store i8 7, ptr %byte, align 1
  call void @escape(ptr %big)
  %v = load i256, ptr %obj, align 1
  ret i256 %v
}
