; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; The EVM operations that have no RISC-V equivalent, reached through intrinsics
; because they have no LLVM opcode. bswap has one and is matched directly.

declare i256 @llvm.riscv.revive.addmod(i256, i256, i256)
declare i256 @llvm.riscv.revive.mulmod(i256, i256, i256)
declare i256 @llvm.riscv.revive.exp(i256, i256)
declare i256 @llvm.riscv.revive.signextend(i256, i256)
declare i256 @llvm.bswap.i256(i256)

define i256 @addmod(i256 %a, i256 %b, i256 %n) {
; CHECK-LABEL: addmod:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.addmod v8, v8, v10, v12
; CHECK-NEXT:    ret
  %r = call i256 @llvm.riscv.revive.addmod(i256 %a, i256 %b, i256 %n)
  ret i256 %r
}

define i256 @mulmod(i256 %a, i256 %b, i256 %n) {
; CHECK-LABEL: mulmod:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.mulmod v8, v8, v10, v12
; CHECK-NEXT:    ret
  %r = call i256 @llvm.riscv.revive.mulmod(i256 %a, i256 %b, i256 %n)
  ret i256 %r
}

define i256 @exp(i256 %a, i256 %b) {
; CHECK-LABEL: exp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.exp256 v8, v8, v10
; CHECK-NEXT:    ret
  %r = call i256 @llvm.riscv.revive.exp(i256 %a, i256 %b)
  ret i256 %r
}

define i256 @signextend(i256 %a, i256 %b) {
; CHECK-LABEL: signextend:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.signextend256 v8, v8, v10
; CHECK-NEXT:    ret
  %r = call i256 @llvm.riscv.revive.signextend(i256 %a, i256 %b)
  ret i256 %r
}

; EVM words are big-endian in memory, so this is everywhere in contract code.
define i256 @bswap(i256 %a) {
; CHECK-LABEL: bswap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.bswap256 v8, v8
; CHECK-NEXT:    ret
  %r = call i256 @llvm.bswap.i256(i256 %a)
  ret i256 %r
}
