; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -riscv-revive-i128 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; The extension's second width: i128 in one vector register, with an instruction
; of its own for every operation i256 has one for. Nothing here passes an i128
; in or out of a function, because the calling convention still only knows the
; wider type; every value travels through memory instead.

define void @add_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: add_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @sub_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sub_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wsub.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = sub i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @mul_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: mul_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wmul.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = mul i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @and_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: and_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wand.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = and i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @or_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: or_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wor.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = or i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @xor_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: xor_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wxor.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = xor i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

; div and rem are the operations whose libcall does not exist, so a width that
; reached one would not link.
define void @udiv_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: udiv_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wdivu.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = udiv i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @sdiv_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sdiv_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wdiv.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = sdiv i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @urem_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: urem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wremu.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = urem i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @srem_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: srem_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wrem.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = srem i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

; A constant divisor is the shape the mid-end would have narrowed to i64 before
; the backend saw it. Straight from IR it stays 128 bits wide, and must still
; reach the instruction rather than a libcall.
define void @udiv_i128_constant(ptr %p, ptr %r) {
; CHECK-LABEL: udiv_i128_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v10, 0(a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI10_0)
; CHECK-NEXT:    addi a0, a0, %lo(.LCPI10_0)
; CHECK-NEXT:    revive.wld v8, 0(a0)
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:    revive.wsrl.i128 v10, v10, a0
; CHECK-NEXT:    revive.wzext.i128 v11, zero
; CHECK-NEXT:    revive.wmul v8, v10, v8
; CHECK-NEXT:    li a0, 132
; CHECK-NEXT:    revive.wsrl v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = udiv i128 %a, 1000
  store i128 %c, ptr %r
  ret void
}

define void @bswap_i128(ptr %p, ptr %r) {
; CHECK-LABEL: bswap_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wbswap.i128 v8, v8
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = call i128 @llvm.bswap.i128(i128 %a)
  store i128 %c, ptr %r
  ret void
}

; Four compares have instructions; the two reversed ones swap the operands.
define void @eq_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: eq_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wseq.i128 a0, v8, v9
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = icmp eq i128 %a, %b
  %z = zext i1 %c to i64
  store i64 %z, ptr %r
  ret void
}

define void @ne_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: ne_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wsne.i128 a0, v8, v9
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = icmp ne i128 %a, %b
  %z = zext i1 %c to i64
  store i64 %z, ptr %r
  ret void
}

define void @ult_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: ult_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wsltu.i128 a0, v8, v9
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = icmp ult i128 %a, %b
  %z = zext i1 %c to i64
  store i64 %z, ptr %r
  ret void
}

define void @slt_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: slt_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wslt.i128 a0, v8, v9
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = icmp slt i128 %a, %b
  %z = zext i1 %c to i64
  store i64 %z, ptr %r
  ret void
}

define void @ugt_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: ugt_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wsltu.i128 a0, v9, v8
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = icmp ugt i128 %a, %b
  %z = zext i1 %c to i64
  store i64 %z, ptr %r
  ret void
}

define void @sgt_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sgt_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wslt.i128 a0, v9, v8
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = icmp sgt i128 %a, %b
  %z = zext i1 %c to i64
  store i64 %z, ptr %r
  ret void
}

; The shift amount is an XLen quantity: a wide one is narrowed first.
define void @shl_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: shl_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    ld a0, 0(a1)
; CHECK-NEXT:    revive.wsll.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = shl i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @lshr_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: lshr_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    ld a0, 0(a1)
; CHECK-NEXT:    revive.wsrl.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = lshr i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @ashr_i128(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: ashr_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    ld a0, 0(a1)
; CHECK-NEXT:    revive.wsra.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = ashr i128 %a, %b
  store i128 %c, ptr %r
  ret void
}

define void @shl_i128_gpr(ptr %p, i64 %s, ptr %r) {
; CHECK-LABEL: shl_i128_gpr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wsll.i128 v8, v8, a1
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %w = zext i64 %s to i128
  %c = shl i128 %a, %w
  store i128 %c, ptr %r
  ret void
}

define void @lshr_i128_gpr(ptr %p, i64 %s, ptr %r) {
; CHECK-LABEL: lshr_i128_gpr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wsrl.i128 v8, v8, a1
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %w = zext i64 %s to i128
  %c = lshr i128 %a, %w
  store i128 %c, ptr %r
  ret void
}

define void @ashr_i128_gpr(ptr %p, i64 %s, ptr %r) {
; CHECK-LABEL: ashr_i128_gpr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wsra.i128 v8, v8, a1
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %w = zext i64 %s to i128
  %c = ashr i128 %a, %w
  store i128 %c, ptr %r
  ret void
}

; An even offset folds into the access, at the width's own encoding.
define void @load_store_offset(ptr %p, ptr %r) {
; CHECK-LABEL: load_store_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 16(a0)
; CHECK-NEXT:    revive.wst.i128 v8, 48(a1)
; CHECK-NEXT:    ret
  %q = getelementptr i128, ptr %p, i64 1
  %v = load i128, ptr %q
  %s = getelementptr i128, ptr %r, i64 3
  store i128 %v, ptr %s
  ret void
}

; Narrower memory has no wide instruction: the value goes through a GPR.
define void @extload_i8(ptr %p, ptr %r) {
; CHECK-LABEL: extload_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    revive.wzext.i128 v9, a0
; CHECK-NEXT:    revive.wand.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  %z = zext i8 %v to i128
  store i128 %z, ptr %r
  ret void
}

define void @extload_i16(ptr %p, ptr %r) {
; CHECK-LABEL: extload_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhu a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    lui a0, 16
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    revive.wzext.i128 v9, a0
; CHECK-NEXT:    revive.wand.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i16, ptr %p
  %z = zext i16 %v to i128
  store i128 %z, ptr %r
  ret void
}

define void @extload_i32(ptr %p, ptr %r) {
; CHECK-LABEL: extload_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwu a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    revive.wzext.i128 v9, a0
; CHECK-NEXT:    revive.wand.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i32, ptr %p
  %z = zext i32 %v to i128
  store i128 %z, ptr %r
  ret void
}

define void @extload_i64(ptr %p, ptr %r) {
; CHECK-LABEL: extload_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    revive.wzext.i128 v9, a0
; CHECK-NEXT:    revive.wand.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i64, ptr %p
  %z = zext i64 %v to i128
  store i128 %z, ptr %r
  ret void
}

define void @sextload_i8(ptr %p, ptr %r) {
; CHECK-LABEL: sextload_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    li a0, 120
; CHECK-NEXT:    revive.wsll.i128 v8, v8, a0
; CHECK-NEXT:    revive.wsra.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i8, ptr %p
  %z = sext i8 %v to i128
  store i128 %z, ptr %r
  ret void
}

define void @sextload_i16(ptr %p, ptr %r) {
; CHECK-LABEL: sextload_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhu a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    li a0, 112
; CHECK-NEXT:    revive.wsll.i128 v8, v8, a0
; CHECK-NEXT:    revive.wsra.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i16, ptr %p
  %z = sext i16 %v to i128
  store i128 %z, ptr %r
  ret void
}

define void @sextload_i32(ptr %p, ptr %r) {
; CHECK-LABEL: sextload_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwu a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sext.w a0, a0
; CHECK-NEXT:    revive.wsext.i128 v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i32, ptr %p
  %z = sext i32 %v to i128
  store i128 %z, ptr %r
  ret void
}

; A whole XLen word has no sign-extending load fragment, so legalization splits
; the sextload into an any-extending one and a sign_extend_inreg of the value.
define void @sextload_i64(ptr %p, ptr %r) {
; CHECK-LABEL: sextload_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    revive.wsext.i128 v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i64, ptr %p
  %z = sext i64 %v to i128
  store i128 %z, ptr %r
  ret void
}

; The stored value is computed rather than loaded, so the narrow store is a
; truncating one rather than a narrower load the combiner folded.
define void @truncstore_i8(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: truncstore_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sb a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %t = trunc i128 %c to i8
  store i8 %t, ptr %r
  ret void
}

define void @truncstore_i16(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: truncstore_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sh a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %t = trunc i128 %c to i16
  store i16 %t, ptr %r
  ret void
}

define void @truncstore_i32(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: truncstore_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sw a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %t = trunc i128 %c to i32
  store i32 %t, ptr %r
  ret void
}

define void @truncstore_i64(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: truncstore_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %t = trunc i128 %c to i64
  store i64 %t, ptr %r
  ret void
}

; sign_extend_inreg is formed after legalization, so it needs patterns of its
; own at the width: narrow to a GPR, sign-extend there, widen back.
define void @sext_inreg_i8(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sext_inreg_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    li a0, 120
; CHECK-NEXT:    revive.wsll.i128 v8, v8, a0
; CHECK-NEXT:    revive.wsra.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %n = trunc i128 %c to i8
  %s = sext i8 %n to i128
  store i128 %s, ptr %r
  ret void
}

define void @sext_inreg_i16(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sext_inreg_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    li a0, 112
; CHECK-NEXT:    revive.wsll.i128 v8, v8, a0
; CHECK-NEXT:    revive.wsra.i128 v8, v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %n = trunc i128 %c to i16
  %s = sext i16 %n to i128
  store i128 %s, ptr %r
  ret void
}

define void @sext_inreg_i32(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sext_inreg_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sext.w a0, a0
; CHECK-NEXT:    revive.wsext.i128 v8, a0
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %c = add i128 %a, %b
  %n = trunc i128 %c to i32
  %s = sext i32 %n to i128
  store i128 %s, ptr %r
  ret void
}

; Counting bits produces an XLen value, which is what the caller wants here.
; A count that must be defined at zero is despeculated into a compare and a
; branch before the backend sees it, exactly as the wider type is in this
; configuration; the zero-undef forms below are the bare instruction.
define void @cpop_i128(ptr %p, ptr %r) {
; CHECK-LABEL: cpop_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wcpop.i128 a0, v8
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = call i128 @llvm.ctpop.i128(i128 %a)
  %n = trunc i128 %c to i64
  store i64 %n, ptr %r
  ret void
}

define void @clz_i128(ptr %p, ptr %r) {
; CHECK-LABEL: clz_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v9, zero
; CHECK-NEXT:    revive.wseq.i128 a0, v8, v9
; CHECK-NEXT:    bnez a0, .LBB41_2
; CHECK-NEXT:  # %bb.1: # %cond.false
; CHECK-NEXT:    revive.wclz.i128 a0, v8
; CHECK-NEXT:    j .LBB41_3
; CHECK-NEXT:  .LBB41_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:  .LBB41_3: # %cond.end
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = call i128 @llvm.ctlz.i128(i128 %a, i1 false)
  %n = trunc i128 %c to i64
  store i64 %n, ptr %r
  ret void
}

define void @ctz_i128(ptr %p, ptr %r) {
; CHECK-LABEL: ctz_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wzext.i128 v9, zero
; CHECK-NEXT:    revive.wseq.i128 a0, v8, v9
; CHECK-NEXT:    bnez a0, .LBB42_2
; CHECK-NEXT:  # %bb.1: # %cond.false
; CHECK-NEXT:    revive.wctz.i128 a0, v8
; CHECK-NEXT:    j .LBB42_3
; CHECK-NEXT:  .LBB42_2:
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:  .LBB42_3: # %cond.end
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = call i128 @llvm.cttz.i128(i128 %a, i1 false)
  %n = trunc i128 %c to i64
  store i64 %n, ptr %r
  ret void
}

define void @clz_zero_undef_i128(ptr %p, ptr %r) {
; CHECK-LABEL: clz_zero_undef_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wclz.i128 a0, v8
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = call i128 @llvm.ctlz.i128(i128 %a, i1 true)
  %n = trunc i128 %c to i64
  store i64 %n, ptr %r
  ret void
}

define void @ctz_zero_undef_i128(ptr %p, ptr %r) {
; CHECK-LABEL: ctz_zero_undef_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wctz.i128 a0, v8
; CHECK-NEXT:    revive.wzext.i128 v8, a0
; CHECK-NEXT:    revive.wtrunc.i128 a0, v8
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %c = call i128 @llvm.cttz.i128(i128 %a, i1 true)
  %n = trunc i128 %c to i64
  store i64 %n, ptr %r
  ret void
}

; There is no wide conditional move, so a select becomes the conditional-branch
; triangle its own pseudo expands to. Both arms are computed, so each sinks into
; a branch of the triangle and the value needs no register copy, which would
; otherwise cost a move of its own at this width.
define void @select_i128(ptr %p, ptr %q, ptr %r, i64 %c) {
; CHECK-LABEL: select_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    beqz a3, .LBB45_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    revive.wsub.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB45_2:
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %x = add i128 %a, %b
  %y = sub i128 %a, %b
  %t = icmp eq i64 %c, 0
  %s = select i1 %t, i128 %x, i128 %y
  store i128 %s, ptr %r
  ret void
}

define void @select_wide_cond(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: select_wide_cond:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wsltu.i128 a0, v8, v9
; CHECK-NEXT:    bnez a0, .LBB46_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    revive.wsub.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB46_2:
; CHECK-NEXT:    revive.wadd.i128 v8, v8, v9
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %x = add i128 %a, %b
  %y = sub i128 %a, %b
  %t = icmp ult i128 %a, %b
  %s = select i1 %t, i128 %x, i128 %y
  store i128 %s, ptr %r
  ret void
}

; Sign-extending into the wider type while the narrow value stays live: the
; pair's low half and the value itself end up in the same register, so the
; extension costs nothing beyond the shift; landing them apart would cost a
; move of the low half as well.
define void @sext_i128_still_live(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: sext_i128_still_live:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    revive.wsra.i128 v9, v8, a0
; CHECK-NEXT:    revive.wst v8, 0(a1)
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    ret
  %v = load i128, ptr %p
  %s = sext i128 %v to i256
  store i256 %s, ptr %q
  store i128 %v, ptr %r
  ret void
}

; A value that fits an XLen register is built there and widened.
define void @const_small(ptr %r) {
; CHECK-LABEL: const_small:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1234
; CHECK-NEXT:    revive.wzext.i128 v8, a1
; CHECK-NEXT:    revive.wst.i128 v8, 0(a0)
; CHECK-NEXT:    ret
  store i128 1234, ptr %r
  ret void
}

define void @const_allones(ptr %r) {
; CHECK-LABEL: const_allones:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    revive.wsext.i128 v8, a1
; CHECK-NEXT:    revive.wst.i128 v8, 0(a0)
; CHECK-NEXT:    ret
  store i128 -1, ptr %r
  ret void
}

; Significant bits at both ends, so no shift of an XLen value reaches it and it
; comes from a pool entry of its own width. The offset of a wide instruction
; cannot carry a relocation, so the address is materialized in full and the load
; takes offset zero.
define void @const_pool(ptr %r) {
; CHECK-LABEL: const_pool:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI50_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI50_0)
; CHECK-NEXT:    revive.wld.i128 v8, 0(a1)
; CHECK-NEXT:    revive.wst.i128 v8, 0(a0)
; CHECK-NEXT:    ret
  store i128 1512366075204170947332355369683137040, ptr %r
  ret void
}

declare i128 @llvm.bswap.i128(i128)
declare i128 @llvm.ctpop.i128(i128)
declare i128 @llvm.ctlz.i128(i128, i1)
declare i128 @llvm.cttz.i128(i128, i1)
