; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Without XReviveVec, i256 is expanded into i64 limbs and passed by reference,
; and none of the extension's behaviour leaks in.

define i256 @add_i256(i256 %a, i256 %b) {
; CHECK-LABEL: add_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld a5, 0(a2)
; CHECK-NEXT:    ld t0, 8(a2)
; CHECK-NEXT:    ld a4, 16(a2)
; CHECK-NEXT:    ld a2, 24(a2)
; CHECK-NEXT:    ld a7, 8(a1)
; CHECK-NEXT:    ld t1, 0(a1)
; CHECK-NEXT:    ld a3, 16(a1)
; CHECK-NEXT:    ld a6, 24(a1)
; CHECK-NEXT:    add t2, a7, t0
; CHECK-NEXT:    add a1, t1, a5
; CHECK-NEXT:    sltu t0, a1, t1
; CHECK-NEXT:    add a5, t2, t0
; CHECK-NEXT:    beq a5, a7, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sltu t0, a5, a7
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    add a4, a3, a4
; CHECK-NEXT:    add a2, a6, a2
; CHECK-NEXT:    add t0, a4, t0
; CHECK-NEXT:    sltu a3, a4, a3
; CHECK-NEXT:    sltu a4, t0, a4
; CHECK-NEXT:    add a2, a2, a3
; CHECK-NEXT:    add a2, a2, a4
; CHECK-NEXT:    sd a1, 0(a0)
; CHECK-NEXT:    sd a5, 8(a0)
; CHECK-NEXT:    sd t0, 16(a0)
; CHECK-NEXT:    sd a2, 24(a0)
; CHECK-NEXT:    ret
  %r = add i256 %a, %b
  ret i256 %r
}

define i64 @cmp_ult(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld a7, 8(a1)
; CHECK-NEXT:    ld a2, 16(a1)
; CHECK-NEXT:    ld a3, 24(a1)
; CHECK-NEXT:    ld t0, 8(a0)
; CHECK-NEXT:    ld a6, 24(a0)
; CHECK-NEXT:    ld a5, 16(a0)
; CHECK-NEXT:    beq a6, a3, .LBB1_3
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sltu a4, a6, a3
; CHECK-NEXT:    bne t0, a7, .LBB1_4
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    ld a1, 0(a1)
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    sltu a0, a0, a1
; CHECK-NEXT:    j .LBB1_5
; CHECK-NEXT:  .LBB1_3:
; CHECK-NEXT:    sltu a4, a5, a2
; CHECK-NEXT:    beq t0, a7, .LBB1_2
; CHECK-NEXT:  .LBB1_4:
; CHECK-NEXT:    sltu a0, t0, a7
; CHECK-NEXT:  .LBB1_5:
; CHECK-NEXT:    xor a1, a6, a3
; CHECK-NEXT:    xor a2, a5, a2
; CHECK-NEXT:    or a1, a2, a1
; CHECK-NEXT:    beqz a1, .LBB1_7
; CHECK-NEXT:  # %bb.6:
; CHECK-NEXT:    mv a0, a4
; CHECK-NEXT:  .LBB1_7:
; CHECK-NEXT:    ret
  %c = icmp ult i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i256 @const_allones() {
; CHECK-LABEL: const_allones:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    sd a1, 0(a0)
; CHECK-NEXT:    sd a1, 8(a0)
; CHECK-NEXT:    sd a1, 16(a0)
; CHECK-NEXT:    sd a1, 24(a0)
; CHECK-NEXT:    ret
  ret i256 -1
}

; Adjacent constant stores may still be merged when the extension is off.
define void @merge_stores(ptr %p) {
; CHECK-LABEL: merge_stores:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sd zero, 0(a0)
; CHECK-NEXT:    sd zero, 8(a0)
; CHECK-NEXT:    sd zero, 16(a0)
; CHECK-NEXT:    sd zero, 24(a0)
; CHECK-NEXT:    ret
  store i64 0, ptr %p
  %q1 = getelementptr i64, ptr %p, i64 1
  store i64 0, ptr %q1
  %q2 = getelementptr i64, ptr %p, i64 2
  store i64 0, ptr %q2
  %q3 = getelementptr i64, ptr %p, i64 3
  store i64 0, ptr %q3
  ret void
}
