; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; The extension pins VLEN to 128 on its own: Zvl128b alone only sets a floor, so
; without a maximum the frame lowering treats every RVV slot as scalable and
; addresses it through vlenb. With the width known, a spill slot is a fixed 32
; bytes at an immediate offset -- no csrr, no multiply.

declare i256 @sink(i256)

define i256 @spill_no_vlenb(ptr %p) {
; CHECK-LABEL: spill_no_vlenb:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -112
; CHECK-NEXT:    .cfi_def_cfa_offset 112
; CHECK-NEXT:    sd ra, 104(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    revive.ld256 v8, 0(a0)
; CHECK-NEXT:    revive.ld256 v10, 0(a0)
; CHECK-NEXT:    revive.st256 v10, 72(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.ld256 v10, 0(a0)
; CHECK-NEXT:    revive.st256 v10, 40(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.ld256 v10, 0(a0)
; CHECK-NEXT:    revive.st256 v10, 8(sp) # 32-byte Folded Spill
; CHECK-NEXT:    call sink
; CHECK-NEXT:    revive.ld256 v10, 72(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.add256 v8, v8, v10
; CHECK-NEXT:    revive.ld256 v10, 40(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.add256 v8, v8, v10
; CHECK-NEXT:    revive.ld256 v10, 8(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.add256 v8, v8, v10
; CHECK-NEXT:    ld ra, 104(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 112
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v0 = load volatile i256, ptr %p
  %v1 = load volatile i256, ptr %p
  %v2 = load volatile i256, ptr %p
  %v3 = load volatile i256, ptr %p
  %c = call i256 @sink(i256 %v0)
  %a1 = add i256 %c, %v1
  %a2 = add i256 %a1, %v2
  %a3 = add i256 %a2, %v3
  ret i256 %a3
}
