; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Four comparisons have instructions; the reversed forms swap operands and the
; rest invert, so all ten predicates must select without expanding.

define i64 @cmp_eq(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_eq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wseq a0, w0, w1
; CHECK-NEXT:    ret
  %c = icmp eq i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_ne(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_ne:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsne a0, w0, w1
; CHECK-NEXT:    ret
  %c = icmp ne i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_ult(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsltu a0, w0, w1
; CHECK-NEXT:    ret
  %c = icmp ult i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_ule(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_ule:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsltu a0, w1, w0
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    ret
  %c = icmp ule i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_ugt(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsltu a0, w1, w0
; CHECK-NEXT:    ret
  %c = icmp ugt i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_uge(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_uge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsltu a0, w0, w1
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    ret
  %c = icmp uge i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_slt(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_slt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wslt a0, w0, w1
; CHECK-NEXT:    ret
  %c = icmp slt i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_sle(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_sle:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wslt a0, w1, w0
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    ret
  %c = icmp sle i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_sgt(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_sgt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wslt a0, w1, w0
; CHECK-NEXT:    ret
  %c = icmp sgt i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_sge(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_sge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wslt a0, w0, w1
; CHECK-NEXT:    xori a0, a0, 1
; CHECK-NEXT:    ret
  %c = icmp sge i256 %a, %b
  %z = zext i1 %c to i64
  ret i64 %z
}

define i64 @cmp_branch(i256 %a, i256 %b) {
; CHECK-LABEL: cmp_branch:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsltu a0, w0, w1
; CHECK-NEXT:    beqz a0, .LBB10_2
; CHECK-NEXT:  # %bb.1: # %t
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:  .LBB10_2: # %f
; CHECK-NEXT:    ret
  %c = icmp ult i256 %a, %b
  br i1 %c, label %t, label %f
t:
  ret i64 1
f:
  ret i64 0
}

