; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -riscv-revive-i128 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

; The narrower width spills and copies through instructions of its own, just as
; the wider one does: a single register rather than a pair, but the same ordinary
; fixed-size stack slots and the same absence of any vector instruction. The
; pressure that forces a spill comes from an inline-asm clobber of the whole
; register file rather than from a call, so that what is pinned is the spill
; itself rather than the calling convention.

; Two slots sixteen bytes apart, because a slot holds the width itself rather
; than the smallest vector register its class could describe; eight bytes of
; alignment, because these accesses need none and asking for the register width
; would realign the frame of every function that spills.
define void @spill_across_clobber(ptr %p, ptr %q, ptr %r, ptr %s) {
; CHECK-LABEL: spill_across_clobber:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wst.i128 v8, 16(sp) # 16-byte Folded Spill
; CHECK-NEXT:    revive.wld.i128 v8, 0(a1)
; CHECK-NEXT:    revive.wst.i128 v8, 0(sp) # 16-byte Folded Spill
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    revive.wld.i128 v8, 16(sp) # 16-byte Folded Reload
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    revive.wld.i128 v8, 0(sp) # 16-byte Folded Reload
; CHECK-NEXT:    revive.wst.i128 v8, 0(a3)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %a = load volatile i128, ptr %p
  %b = load volatile i128, ptr %q
  call void asm sideeffect "", "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19},~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29},~{v30},~{v31}"()
  store volatile i128 %a, ptr %r
  store volatile i128 %b, ptr %s
  ret void
}

; A value that reaches the join in a different register on each path needs a
; register move, since both incoming values are still live there and neither can
; be coalesced with the result.
define void @copy_is_one_instruction(ptr %p, ptr %q, ptr %r, i64 %c) {
; CHECK-LABEL: copy_is_one_instruction:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wld.i128 v9, 0(a1)
; CHECK-NEXT:    revive.wmv.i128 v10, v8
; CHECK-NEXT:    beqz a3, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %else
; CHECK-NEXT:    revive.wmv.i128 v10, v9
; CHECK-NEXT:  .LBB1_2: # %join
; CHECK-NEXT:    revive.wst.i128 v10, 0(a2)
; CHECK-NEXT:    revive.wst.i128 v8, 0(a2)
; CHECK-NEXT:    revive.wst.i128 v9, 0(a2)
; CHECK-NEXT:    ret
entry:
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %t = icmp eq i64 %c, 0
  br i1 %t, label %then, label %else

then:
  br label %join

else:
  br label %join

join:
  %v = phi i128 [ %a, %then ], [ %b, %else ]
  store volatile i128 %v, ptr %r
  store volatile i128 %a, ptr %r
  store volatile i128 %b, ptr %r
  ret void
}
