; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Values that fit an XLen register are built there and widened; only genuinely
; wide constants reach the pool. -1 has 256 active bits but one significant bit,
; so it takes the sign-extending form.

define i256 @const_zero() {
; CHECK-LABEL: const_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wzext w0, zero
; CHECK-NEXT:    ret
  ret i256 0
}

define i256 @const_small() {
; CHECK-LABEL: const_small:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 1234
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  ret i256 1234
}

define i256 @const_mask32() {
; CHECK-LABEL: const_mask32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  ret i256 4294967295
}

define i256 @const_mask64() {
; CHECK-LABEL: const_mask64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    revive.wzext w0, a0
; CHECK-NEXT:    ret
  ret i256 18446744073709551615
}

define i256 @const_allones() {
; CHECK-LABEL: const_allones:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    revive.wsext w0, a0
; CHECK-NEXT:    ret
  ret i256 -1
}

define i256 @const_negative() {
; CHECK-LABEL: const_negative:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, -1234
; CHECK-NEXT:    revive.wsext w0, a0
; CHECK-NEXT:    ret
  ret i256 -1234
}

; Wider than an XLen register: this one has to come from the pool.
define i256 @const_wide() {
; CHECK-LABEL: const_wide:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(.LCPI6_0)
; CHECK-NEXT:    revive.wld w0, %lo(.LCPI6_0)(a0)
; CHECK-NEXT:    ret
  ret i256 6277101733925179126504886505003981583386072424808101969920
}

define i256 @const_operand(i256 %a) {
; CHECK-LABEL: const_operand:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    revive.wzext w1, a0
; CHECK-NEXT:    revive.wand w0, w0, w1
; CHECK-NEXT:    ret
  %r = and i256 %a, 4294967295
  ret i256 %r
}
