; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,ZMMUL
; RUN: llc -mtriple=riscv64 -mattr=+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,NOMUL

; Widened operands with a truncated result: the wide instruction would be doing
; XLen work in a 256-bit register, so the scalar one is selected instead.
; Multiply is the exception -- scalar MUL needs Zmmul -- hence the second run.

define i64 @narrow_add(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = add i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

define i64 @narrow_sub(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_sub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sub a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = sub i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

define i64 @narrow_and(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = and i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

define i64 @narrow_or(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_or:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = or i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

define i64 @narrow_xor(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_xor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xor a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = xor i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

define i64 @narrow_mul(i64 %a, i64 %b) {
; ZMMUL-LABEL: narrow_mul:
; ZMMUL:       # %bb.0:
; ZMMUL-NEXT:    mul a0, a0, a1
; ZMMUL-NEXT:    ret
;
; NOMUL-LABEL: narrow_mul:
; NOMUL:       # %bb.0:
; NOMUL-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; NOMUL-NEXT:    revive.wzext v8, a0
; NOMUL-NEXT:    revive.wzext v10, a1
; NOMUL-NEXT:    revive.wmul v8, v8, v10
; NOMUL-NEXT:    revive.wtrunc a0, v8
; NOMUL-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = mul i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

; Zero extension preserves unsigned order, so compares narrow too.
define i64 @narrow_ult(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sltu a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %c = icmp ult i256 %x, %y
  %r = zext i1 %c to i64
  ret i64 %r
}

define i64 @narrow_ugt(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sltu a0, a1, a0
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %c = icmp ugt i256 %x, %y
  %r = zext i1 %c to i64
  ret i64 %r
}

; The wider LMULs narrow the same way.
define i64 @narrow_add_512(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_add_512:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i512
  %y = zext i64 %b to i512
  %r = add i512 %x, %y
  %t = trunc i512 %r to i64
  ret i64 %t
}

define i64 @narrow_add_1024(i64 %a, i64 %b) {
; CHECK-LABEL: narrow_add_1024:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %x = zext i64 %a to i1024
  %y = zext i64 %b to i1024
  %r = add i1024 %x, %y
  %t = trunc i1024 %r to i64
  ret i64 %t
}

; Division is not narrowed: its low bits depend on the whole operand.
define i64 @no_narrow_udiv(i64 %a, i64 %b) {
; CHECK-LABEL: no_narrow_udiv:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wzext v8, a0
; CHECK-NEXT:    revive.wzext v10, a1
; CHECK-NEXT:    revive.wdivu v8, v8, v10
; CHECK-NEXT:    revive.wtrunc a0, v8
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = udiv i256 %x, %y
  %t = trunc i256 %r to i64
  ret i64 %t
}

; Nor is a shift -- bits enter the low half from above.
define i64 @no_narrow_lshr(i64 %a) {
; CHECK-LABEL: no_narrow_lshr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wzext v8, a0
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:    revive.wsrl v8, v8, a0
; CHECK-NEXT:    revive.wtrunc a0, v8
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %r = lshr i256 %x, 3
  %t = trunc i256 %r to i64
  ret i64 %t
}

; A signed compare of zero-extended operands is not the signed scalar compare.
define i64 @no_narrow_slt(i64 %a, i64 %b) {
; CHECK-LABEL: no_narrow_slt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wzext v8, a0
; CHECK-NEXT:    revive.wzext v10, a1
; CHECK-NEXT:    revive.wslt a0, v8, v10
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %c = icmp slt i256 %x, %y
  %r = zext i1 %c to i64
  ret i64 %r
}

; Used wide as well as narrow: narrowing must not delete the wide add.
define i256 @narrow_and_wide_use(i64 %a, i64 %b, ptr %p) {
; CHECK-LABEL: narrow_and_wide_use:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    revive.wzext v8, a0
; CHECK-NEXT:    revive.wzext v10, a1
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    sd a0, 0(a2)
; CHECK-NEXT:    ret
  %x = zext i64 %a to i256
  %y = zext i64 %b to i256
  %r = add i256 %x, %y
  %t = trunc i256 %r to i64
  store i64 %t, ptr %p
  ret i256 %r
}
