; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Wide values spill to ordinary fixed-size stack slots addressed off the stack
; pointer. Nothing here may query the vector length or realign the stack: the
; wide registers are a file of their own, not part of the vector file.

declare i256 @opaque(i256, i256, i256)

define i256 @spill_across_calls(i256 %a0, i256 %a1, i256 %a2, i256 %a3, i256 %a4, i256 %a5, i256 %a6, i256 %a7, i256 %a8, i256 %a9) {
; CHECK-LABEL: spill_across_calls:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -336
; CHECK-NEXT:    .cfi_def_cfa_offset 336
; CHECK-NEXT:    sd ra, 328(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    revive.wst v22, 296(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wst v20, 232(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wst v18, 136(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wst v16, 72(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wst v14, 40(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wst v10, 200(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v14, 368(sp)
; CHECK-NEXT:    revive.wst v14, 264(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v14, 336(sp)
; CHECK-NEXT:    revive.wst v14, 104(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wst v8, 168(sp) # 32-byte Folded Spill
; CHECK-NEXT:    call opaque
; CHECK-NEXT:    revive.wst v8, 8(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v8, 40(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wld v10, 72(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wld v12, 136(sp) # 32-byte Folded Reload
; CHECK-NEXT:    call opaque
; CHECK-NEXT:    revive.wst v8, 136(sp) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v8, 232(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wld v10, 296(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wld v12, 104(sp) # 32-byte Folded Reload
; CHECK-NEXT:    call opaque
; CHECK-NEXT:    revive.wld v10, 8(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wld v12, 136(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v10, v10, v12
; CHECK-NEXT:    revive.wadd v8, v10, v8
; CHECK-NEXT:    revive.wld v10, 264(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    revive.wld v10, 168(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    revive.wld v10, 200(sp) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    ld ra, 328(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 336
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %c0 = call i256 @opaque(i256 %a0, i256 %a1, i256 %a2)
  %c1 = call i256 @opaque(i256 %a3, i256 %a4, i256 %a5)
  %c2 = call i256 @opaque(i256 %a6, i256 %a7, i256 %a8)
  %t0 = add i256 %c0, %c1
  %t1 = add i256 %t0, %c2
  %t2 = add i256 %t1, %a9
  %t3 = add i256 %t2, %a0
  %t4 = add i256 %t3, %a1
  ret i256 %t4
}

define i256 @copy_is_one_instruction(i256 %a, i256 %b, i1 %cond) {
; CHECK-LABEL: copy_is_one_instruction:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v12, v8
; CHECK-NEXT:    beqz a0, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %then
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vmv2r.v v10, v12
; CHECK-NEXT:    call opaque
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v12, v8
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:  .LBB1_2: # %join
; CHECK-NEXT:    vmv2r.v v8, v12
; CHECK-NEXT:    ret
  br i1 %cond, label %then, label %else

then:
  %x = call i256 @opaque(i256 %b, i256 %a, i256 %a)
  br label %join

else:
  br label %join

join:
  %p = phi i256 [ %x, %then ], [ %a, %else ]
  ret i256 %p
}
