; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec,+unaligned-scalar-mem \
; RUN:   -riscv-revive-i128 -verify-machineinstrs < %s | FileCheck %s

; The offset of a wide access is even at either width, so an odd one is added to
; the address instead. Only a byte-aligned access can reach an odd address, and
; it only stays a single wide access where unaligned scalar memory is allowed, so
; this is the one configuration where the distinction shows.

define void @load_odd_offset(ptr %p, ptr %r) {
; CHECK-LABEL: load_odd_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 17
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %q = getelementptr i8, ptr %p, i64 17
  %v = load i128, ptr %q, align 1
  store i128 %v, ptr %r, align 1
  ret void
}

define void @store_odd_offset(ptr %p, ptr %r) {
; CHECK-LABEL: store_odd_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 0(a0)
; CHECK-NEXT:    addi a1, a1, -3
; CHECK-NEXT:    revive.wst.i128 v8, 0(a1)
; CHECK-NEXT:    ret
  %v = load i128, ptr %p, align 1
  %q = getelementptr i8, ptr %r, i64 -3
  store i128 %v, ptr %q, align 1
  ret void
}

define void @load_store_even_offset(ptr %p, ptr %r) {
; CHECK-LABEL: load_store_even_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wld.i128 v8, 18(a0)
; CHECK-NEXT:    revive.wst.i128 v8, -4(a1)
; CHECK-NEXT:    ret
  %q = getelementptr i8, ptr %p, i64 18
  %v = load i128, ptr %q, align 1
  %s = getelementptr i8, ptr %r, i64 -4
  store i128 %v, ptr %s, align 1
  ret void
}
