; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -riscv-revive-i128 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,I128
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,NOI128

; Passing the narrower wide type. Where the option has made i128 a machine type
; it travels in a single vector register, and where it has not it promotes to
; i256 and takes a whole pair. Both configurations are pinned here, so what the
; option saves at a call is visible in one place.

declare i128 @sink2(i128, i128)
declare i32 @vsink(i32, ...)

; One register in, one register out: the argument registers are the singles
; v8-v23 and the return register is the first of them.
define i128 @arg_passthrough(i128 %a, i128 %b) {
; I128-LABEL: arg_passthrough:
; I128:       # %bb.0:
; I128-NEXT:    revive.wmv.i128 v8, v9
; I128-NEXT:    ret
;
; NOI128-LABEL: arg_passthrough:
; NOI128:       # %bb.0:
; NOI128-NEXT:    revive.wmv v8, v10
; NOI128-NEXT:    ret
  ret i128 %b
}

; A pair and a single alternating, pair first. The pair in v8m2 covers v8 and v9,
; so the first single is v10; that single in turn covers half of v10m2, so the
; second pair is v12m2, leaving v11 as the next free single.
define i128 @mixed_pair_first(i256 %a, i128 %b, i256 %c, i128 %d) {
; I128-LABEL: mixed_pair_first:
; I128:       # %bb.0:
; I128-NEXT:    revive.wadd.i128 v8, v8, v10
; I128-NEXT:    revive.wadd.i128 v8, v8, v12
; I128-NEXT:    revive.wadd.i128 v8, v8, v11
; I128-NEXT:    ret
;
; NOI128-LABEL: mixed_pair_first:
; NOI128:       # %bb.0:
; NOI128-NEXT:    revive.wadd v8, v8, v10
; NOI128-NEXT:    revive.wadd v8, v8, v12
; NOI128-NEXT:    revive.wadd v8, v8, v14
; NOI128-NEXT:    ret
  %lo.a = trunc i256 %a to i128
  %lo.c = trunc i256 %c to i128
  %s = add i128 %lo.a, %b
  %t = add i128 %s, %lo.c
  %r = add i128 %t, %d
  ret i128 %r
}

; The same list the other way round. The single in v8 blocks v8m2, so the first
; pair is v10m2; v9 is untouched by that pair and takes the second single, and
; the second pair follows in v12m2.
define i128 @mixed_single_first(i128 %a, i256 %b, i128 %c, i256 %d) {
; I128-LABEL: mixed_single_first:
; I128:       # %bb.0:
; I128-NEXT:    revive.wadd.i128 v8, v8, v10
; I128-NEXT:    revive.wadd.i128 v8, v8, v9
; I128-NEXT:    revive.wadd.i128 v8, v8, v12
; I128-NEXT:    ret
;
; NOI128-LABEL: mixed_single_first:
; NOI128:       # %bb.0:
; NOI128-NEXT:    revive.wadd v8, v8, v10
; NOI128-NEXT:    revive.wadd v8, v8, v12
; NOI128-NEXT:    revive.wadd v8, v8, v14
; NOI128-NEXT:    ret
  %lo.b = trunc i256 %b to i128
  %lo.d = trunc i256 %d to i128
  %s = add i128 %a, %lo.b
  %t = add i128 %s, %c
  %r = add i128 %t, %lo.d
  ret i128 %r
}

; More arguments than there are singles: the last two arrive on the stack, in
; slots of the type's own size but only XLen-aligned, because these accesses
; need no alignment and asking for more would realign the caller's frame.
define i128 @arg_stack(i128 %a0, i128 %a1, i128 %a2, i128 %a3, i128 %a4,
; I128-LABEL: arg_stack:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 16(sp)
; I128-NEXT:    revive.wld.i128 v9, 0(sp)
; I128-NEXT:    revive.wadd.i128 v8, v9, v8
; I128-NEXT:    ret
;
; NOI128-LABEL: arg_stack:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a0, 296(sp)
; NOI128-NEXT:    ld a1, 288(sp)
; NOI128-NEXT:    ld a2, 264(sp)
; NOI128-NEXT:    ld a3, 256(sp)
; NOI128-NEXT:    revive.wzext v8, a0
; NOI128-NEXT:    revive.wzext v10, a1
; NOI128-NEXT:    revive.wzext v12, a2
; NOI128-NEXT:    li a0, 64
; NOI128-NEXT:    revive.wsll v8, v8, a0
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wzext v10, a3
; NOI128-NEXT:    revive.wsll v12, v12, a0
; NOI128-NEXT:    revive.wor v10, v10, v12
; NOI128-NEXT:    revive.wadd v8, v10, v8
; NOI128-NEXT:    ret
                       i128 %a5, i128 %a6, i128 %a7, i128 %a8, i128 %a9,
                       i128 %a10, i128 %a11, i128 %a12, i128 %a13, i128 %a14,
                       i128 %a15, i128 %a16, i128 %a17) {
  %r = add i128 %a16, %a17
  ret i128 %r
}

; The same assignment seen from the caller: fifteen copies and two stores, with
; no marshalling through memory for the arguments that fit in registers.
define i128 @call_stack(i128 %a) {
; I128-LABEL: call_stack:
; I128:       # %bb.0:
; I128-NEXT:    addi sp, sp, -48
; I128-NEXT:    .cfi_def_cfa_offset 48
; I128-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; I128-NEXT:    .cfi_offset ra, -8
; I128-NEXT:    revive.wst.i128 v8, 16(sp)
; I128-NEXT:    revive.wst.i128 v8, 0(sp)
; I128-NEXT:    revive.wmv.i128 v9, v8
; I128-NEXT:    revive.wmv.i128 v10, v8
; I128-NEXT:    revive.wmv.i128 v11, v8
; I128-NEXT:    revive.wmv.i128 v12, v8
; I128-NEXT:    revive.wmv.i128 v13, v8
; I128-NEXT:    revive.wmv.i128 v14, v8
; I128-NEXT:    revive.wmv.i128 v15, v8
; I128-NEXT:    revive.wmv.i128 v16, v8
; I128-NEXT:    revive.wmv.i128 v17, v8
; I128-NEXT:    revive.wmv.i128 v18, v8
; I128-NEXT:    revive.wmv.i128 v19, v8
; I128-NEXT:    revive.wmv.i128 v20, v8
; I128-NEXT:    revive.wmv.i128 v21, v8
; I128-NEXT:    revive.wmv.i128 v22, v8
; I128-NEXT:    revive.wmv.i128 v23, v8
; I128-NEXT:    call arg_stack
; I128-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; I128-NEXT:    .cfi_restore ra
; I128-NEXT:    addi sp, sp, 48
; I128-NEXT:    .cfi_def_cfa_offset 0
; I128-NEXT:    ret
;
; NOI128-LABEL: call_stack:
; NOI128:       # %bb.0:
; NOI128-NEXT:    addi sp, sp, -336
; NOI128-NEXT:    .cfi_def_cfa_offset 336
; NOI128-NEXT:    sd ra, 328(sp) # 8-byte Folded Spill
; NOI128-NEXT:    .cfi_offset ra, -8
; NOI128-NEXT:    revive.wst v8, 288(sp)
; NOI128-NEXT:    revive.wst v8, 256(sp)
; NOI128-NEXT:    revive.wst v8, 224(sp)
; NOI128-NEXT:    revive.wst v8, 192(sp)
; NOI128-NEXT:    revive.wst v8, 160(sp)
; NOI128-NEXT:    revive.wst v8, 128(sp)
; NOI128-NEXT:    revive.wst v8, 96(sp)
; NOI128-NEXT:    revive.wst v8, 64(sp)
; NOI128-NEXT:    revive.wst v8, 32(sp)
; NOI128-NEXT:    revive.wst v8, 0(sp)
; NOI128-NEXT:    revive.wmv v10, v8
; NOI128-NEXT:    revive.wmv v12, v8
; NOI128-NEXT:    revive.wmv v14, v8
; NOI128-NEXT:    revive.wmv v16, v8
; NOI128-NEXT:    revive.wmv v18, v8
; NOI128-NEXT:    revive.wmv v20, v8
; NOI128-NEXT:    revive.wmv v22, v8
; NOI128-NEXT:    call arg_stack
; NOI128-NEXT:    ld ra, 328(sp) # 8-byte Folded Reload
; NOI128-NEXT:    .cfi_restore ra
; NOI128-NEXT:    addi sp, sp, 336
; NOI128-NEXT:    .cfi_def_cfa_offset 0
; NOI128-NEXT:    ret
  %r = call i128 @arg_stack(i128 %a, i128 %a, i128 %a, i128 %a, i128 %a,
                            i128 %a, i128 %a, i128 %a, i128 %a, i128 %a,
                            i128 %a, i128 %a, i128 %a, i128 %a, i128 %a,
                            i128 %a, i128 %a, i128 %a)
  ret i128 %r
}

; Marshalling in both directions at one call site: the arguments swap places on
; the way in and the result comes back in the first register.
define i128 @call_swapped(i128 %a, i128 %b) {
; I128-LABEL: call_swapped:
; I128:       # %bb.0:
; I128-NEXT:    addi sp, sp, -16
; I128-NEXT:    .cfi_def_cfa_offset 16
; I128-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; I128-NEXT:    .cfi_offset ra, -8
; I128-NEXT:    revive.wmv.i128 v10, v8
; I128-NEXT:    revive.wmv.i128 v8, v9
; I128-NEXT:    revive.wmv.i128 v9, v10
; I128-NEXT:    call sink2
; I128-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; I128-NEXT:    .cfi_restore ra
; I128-NEXT:    addi sp, sp, 16
; I128-NEXT:    .cfi_def_cfa_offset 0
; I128-NEXT:    ret
;
; NOI128-LABEL: call_swapped:
; NOI128:       # %bb.0:
; NOI128-NEXT:    addi sp, sp, -16
; NOI128-NEXT:    .cfi_def_cfa_offset 16
; NOI128-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NOI128-NEXT:    .cfi_offset ra, -8
; NOI128-NEXT:    revive.wmv v12, v8
; NOI128-NEXT:    revive.wmv v8, v10
; NOI128-NEXT:    revive.wmv v10, v12
; NOI128-NEXT:    call sink2
; NOI128-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NOI128-NEXT:    .cfi_restore ra
; NOI128-NEXT:    addi sp, sp, 16
; NOI128-NEXT:    .cfi_def_cfa_offset 0
; NOI128-NEXT:    ret
  %r = call i128 @sink2(i128 %b, i128 %a)
  ret i128 %r
}

; revive gives its internal functions fastcc, so that path matters as much.
define fastcc i128 @fastcc_callee(i128 %a, i128 %b) {
; I128-LABEL: fastcc_callee:
; I128:       # %bb.0:
; I128-NEXT:    revive.wadd.i128 v8, v8, v9
; I128-NEXT:    ret
;
; NOI128-LABEL: fastcc_callee:
; NOI128:       # %bb.0:
; NOI128-NEXT:    revive.wadd v8, v8, v10
; NOI128-NEXT:    ret
  %r = add i128 %a, %b
  ret i128 %r
}

define i128 @call_fastcc(i128 %a, i128 %b) {
; I128-LABEL: call_fastcc:
; I128:       # %bb.0:
; I128-NEXT:    addi sp, sp, -16
; I128-NEXT:    .cfi_def_cfa_offset 16
; I128-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; I128-NEXT:    .cfi_offset ra, -8
; I128-NEXT:    revive.wmv.i128 v10, v8
; I128-NEXT:    revive.wmv.i128 v8, v9
; I128-NEXT:    revive.wmv.i128 v9, v10
; I128-NEXT:    call fastcc_callee
; I128-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; I128-NEXT:    .cfi_restore ra
; I128-NEXT:    addi sp, sp, 16
; I128-NEXT:    .cfi_def_cfa_offset 0
; I128-NEXT:    ret
;
; NOI128-LABEL: call_fastcc:
; NOI128:       # %bb.0:
; NOI128-NEXT:    addi sp, sp, -16
; NOI128-NEXT:    .cfi_def_cfa_offset 16
; NOI128-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NOI128-NEXT:    .cfi_offset ra, -8
; NOI128-NEXT:    revive.wmv v12, v8
; NOI128-NEXT:    revive.wmv v8, v10
; NOI128-NEXT:    revive.wmv v10, v12
; NOI128-NEXT:    call fastcc_callee
; NOI128-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NOI128-NEXT:    .cfi_restore ra
; NOI128-NEXT:    addi sp, sp, 16
; NOI128-NEXT:    .cfi_def_cfa_offset 0
; NOI128-NEXT:    ret
  %r = call fastcc i128 @fastcc_callee(i128 %b, i128 %a)
  ret i128 %r
}

; fastcc runs out of the same sixteen singles and falls back to the same slots.
define fastcc i128 @fastcc_arg_stack(i128 %a0, i128 %a1, i128 %a2, i128 %a3,
; I128-LABEL: fastcc_arg_stack:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 16(sp)
; I128-NEXT:    revive.wld.i128 v9, 0(sp)
; I128-NEXT:    revive.wadd.i128 v8, v9, v8
; I128-NEXT:    ret
;
; NOI128-LABEL: fastcc_arg_stack:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a0, 296(sp)
; NOI128-NEXT:    ld a1, 288(sp)
; NOI128-NEXT:    ld a2, 264(sp)
; NOI128-NEXT:    ld a3, 256(sp)
; NOI128-NEXT:    revive.wzext v8, a0
; NOI128-NEXT:    revive.wzext v10, a1
; NOI128-NEXT:    revive.wzext v12, a2
; NOI128-NEXT:    li a0, 64
; NOI128-NEXT:    revive.wsll v8, v8, a0
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wzext v10, a3
; NOI128-NEXT:    revive.wsll v12, v12, a0
; NOI128-NEXT:    revive.wor v10, v10, v12
; NOI128-NEXT:    revive.wadd v8, v10, v8
; NOI128-NEXT:    ret
                                     i128 %a4, i128 %a5, i128 %a6, i128 %a7,
                                     i128 %a8, i128 %a9, i128 %a10, i128 %a11,
                                     i128 %a12, i128 %a13, i128 %a14,
                                     i128 %a15, i128 %a16, i128 %a17) {
  %r = add i128 %a16, %a17
  ret i128 %r
}

; A variadic argument of either wide type goes in a vector register just as a
; fixed one does, and consumes no integer register on the way: the plain integer
; argument that follows it lands in a1 at both widths.
define i32 @call_vararg_i128(i128 %a, i32 %n) {
; CHECK-LABEL: call_vararg_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    mv a1, a0
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    call vsink
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %r = call i32 (i32, ...) @vsink(i32 1, i128 %a, i32 %n)
  ret i32 %r
}

define i32 @call_vararg_i256(i256 %a, i32 %n) {
; CHECK-LABEL: call_vararg_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    mv a1, a0
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    call vsink
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %r = call i32 (i32, ...) @vsink(i32 1, i256 %a, i32 %n)
  ret i32 %r
}
