; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -riscv-revive-i128 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=I128
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=NOI128

; Converting between the two wide types, which only i128 being a machine type of
; its own makes possible: one register is half of a pair, so the conversions are
; subregister moves rather than the limb arithmetic the other configuration has
; to fall back on. Both are pinned here, so the difference the option makes is
; visible in one place.

; The wide value is computed, so the truncation is a real one rather than a
; narrower load the combiner folded.
define void @trunc_i256_to_i128(ptr %p, ptr %q, ptr %r) {
; I128-LABEL: trunc_i256_to_i128:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld v8, 0(a0)
; I128-NEXT:    revive.wld v10, 0(a1)
; I128-NEXT:    revive.wadd v8, v8, v10
; I128-NEXT:    revive.wst.i128 v8, 0(a2)
; I128-NEXT:    ret
;
; NOI128-LABEL: trunc_i256_to_i128:
; NOI128:       # %bb.0:
; NOI128-NEXT:    revive.wld v8, 0(a0)
; NOI128-NEXT:    revive.wld v10, 0(a1)
; NOI128-NEXT:    li a0, 64
; NOI128-NEXT:    revive.wadd v8, v8, v10
; NOI128-NEXT:    revive.wtrunc a1, v8
; NOI128-NEXT:    revive.wsrl v8, v8, a0
; NOI128-NEXT:    revive.wtrunc a0, v8
; NOI128-NEXT:    sd a1, 0(a2)
; NOI128-NEXT:    sd a0, 8(a2)
; NOI128-NEXT:    ret
  %a = load i256, ptr %p
  %b = load i256, ptr %q
  %c = add i256 %a, %b
  %t = trunc i256 %c to i128
  store i128 %t, ptr %r
  ret void
}

define void @zext_i128_to_i256(ptr %p, ptr %r) {
; I128-LABEL: zext_i128_to_i256:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 0(a0)
; I128-NEXT:    revive.wzext.i128 v9, zero
; I128-NEXT:    revive.wst v8, 0(a1)
; I128-NEXT:    ret
;
; NOI128-LABEL: zext_i128_to_i256:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a2, 8(a0)
; NOI128-NEXT:    ld a0, 0(a0)
; NOI128-NEXT:    revive.wzext v8, a2
; NOI128-NEXT:    li a2, 64
; NOI128-NEXT:    revive.wsll v8, v8, a2
; NOI128-NEXT:    revive.wzext v10, a0
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wst v8, 0(a1)
; NOI128-NEXT:    ret
  %v = load i128, ptr %p
  %z = zext i128 %v to i256
  store i256 %z, ptr %r
  ret void
}

define void @sext_i128_to_i256(ptr %p, ptr %r) {
; I128-LABEL: sext_i128_to_i256:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 0(a0)
; I128-NEXT:    li a0, 127
; I128-NEXT:    revive.wsra.i128 v9, v8, a0
; I128-NEXT:    revive.wst v8, 0(a1)
; I128-NEXT:    ret
;
; NOI128-LABEL: sext_i128_to_i256:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a2, 8(a0)
; NOI128-NEXT:    ld a0, 0(a0)
; NOI128-NEXT:    revive.wsext v8, a2
; NOI128-NEXT:    li a2, 64
; NOI128-NEXT:    revive.wsll v8, v8, a2
; NOI128-NEXT:    revive.wzext v10, a0
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wst v8, 0(a1)
; NOI128-NEXT:    ret
  %v = load i128, ptr %p
  %s = sext i128 %v to i256
  store i256 %s, ptr %r
  ret void
}

; Promoting an i100 forms an any_extend to the wider type, with the mask that
; makes the extension a zero one applied afterwards.
define void @anyext_i100_to_i256(ptr %p, ptr %r) {
; I128-LABEL: anyext_i100_to_i256:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 0(a0)
; I128-NEXT:    li a0, -1
; I128-NEXT:    revive.wsext v10, a0
; I128-NEXT:    li a0, 156
; I128-NEXT:    revive.wsrl v10, v10, a0
; I128-NEXT:    revive.wand v8, v8, v10
; I128-NEXT:    revive.wst v8, 0(a1)
; I128-NEXT:    ret
;
; NOI128-LABEL: anyext_i100_to_i256:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a2, 8(a0)
; NOI128-NEXT:    ld a0, 0(a0)
; NOI128-NEXT:    revive.wzext v8, a2
; NOI128-NEXT:    li a2, 64
; NOI128-NEXT:    revive.wzext v10, a0
; NOI128-NEXT:    li a0, -1
; NOI128-NEXT:    revive.wsll v8, v8, a2
; NOI128-NEXT:    li a2, 156
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wsext v10, a0
; NOI128-NEXT:    revive.wsrl v10, v10, a2
; NOI128-NEXT:    revive.wand v8, v8, v10
; NOI128-NEXT:    revive.wst v8, 0(a1)
; NOI128-NEXT:    ret
  %v = load i128, ptr %p
  %n = trunc i128 %v to i100
  %z = zext i100 %n to i256
  store i256 %z, ptr %r
  ret void
}

; The wide value is stored as well, so the truncation stays a wide instruction
; rather than becoming a narrower load.
define void @trunc_i128_to_i64(ptr %p, ptr %q, ptr %r) {
; I128-LABEL: trunc_i128_to_i64:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 0(a0)
; I128-NEXT:    revive.wtrunc.i128 a0, v8
; I128-NEXT:    sd a0, 0(a1)
; I128-NEXT:    revive.wst.i128 v8, 0(a2)
; I128-NEXT:    ret
;
; NOI128-LABEL: trunc_i128_to_i64:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a3, 0(a0)
; NOI128-NEXT:    revive.wzext v8, zero
; NOI128-NEXT:    ld a0, 8(a0)
; NOI128-NEXT:    revive.wzext v10, a3
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wtrunc a3, v8
; NOI128-NEXT:    sd a3, 0(a1)
; NOI128-NEXT:    sd a3, 0(a2)
; NOI128-NEXT:    sd a0, 8(a2)
; NOI128-NEXT:    ret
  %v = load i128, ptr %p
  %t = trunc i128 %v to i64
  store i64 %t, ptr %q
  store i128 %v, ptr %r
  ret void
}

; A type between the widths promotes to i128 rather than to i256, so the masks
; the promotion needs are wide instructions of the narrower width.
define void @udiv_i100(ptr %p, ptr %q, ptr %r) {
; I128-LABEL: udiv_i100:
; I128:       # %bb.0:
; I128-NEXT:    revive.wld.i128 v8, 0(a0)
; I128-NEXT:    revive.wld.i128 v9, 0(a1)
; I128-NEXT:    li a0, -1
; I128-NEXT:    li a1, 28
; I128-NEXT:    revive.wsext.i128 v10, a0
; I128-NEXT:    revive.wsrl.i128 v10, v10, a1
; I128-NEXT:    revive.wand.i128 v8, v8, v10
; I128-NEXT:    revive.wand.i128 v9, v9, v10
; I128-NEXT:    revive.wdivu.i128 v8, v8, v9
; I128-NEXT:    revive.wst.i128 v8, 0(a2)
; I128-NEXT:    ret
;
; NOI128-LABEL: udiv_i100:
; NOI128:       # %bb.0:
; NOI128-NEXT:    ld a3, 8(a0)
; NOI128-NEXT:    ld a0, 0(a0)
; NOI128-NEXT:    ld a4, 0(a1)
; NOI128-NEXT:    ld a1, 8(a1)
; NOI128-NEXT:    revive.wzext v8, a3
; NOI128-NEXT:    revive.wzext v10, a0
; NOI128-NEXT:    li a0, 64
; NOI128-NEXT:    revive.wzext v12, a1
; NOI128-NEXT:    li a1, -1
; NOI128-NEXT:    revive.wsll v8, v8, a0
; NOI128-NEXT:    revive.wor v8, v10, v8
; NOI128-NEXT:    revive.wzext v10, a4
; NOI128-NEXT:    li a3, 156
; NOI128-NEXT:    revive.wsll v12, v12, a0
; NOI128-NEXT:    revive.wor v10, v10, v12
; NOI128-NEXT:    revive.wsext v12, a1
; NOI128-NEXT:    revive.wsrl v12, v12, a3
; NOI128-NEXT:    revive.wand v8, v8, v12
; NOI128-NEXT:    revive.wand v10, v10, v12
; NOI128-NEXT:    revive.wdivu v8, v8, v10
; NOI128-NEXT:    revive.wtrunc a1, v8
; NOI128-NEXT:    revive.wsrl v8, v8, a0
; NOI128-NEXT:    revive.wtrunc a0, v8
; NOI128-NEXT:    sd a1, 0(a2)
; NOI128-NEXT:    sd a0, 8(a2)
; NOI128-NEXT:    ret
  %a = load i128, ptr %p
  %b = load i128, ptr %q
  %x = trunc i128 %a to i100
  %y = trunc i128 %b to i100
  %d = udiv i100 %x, %y
  %z = zext i100 %d to i128
  store i128 %z, ptr %r
  ret void
}
