; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; There is no wide conditional move, so a wide select becomes the same
; conditional-branch triangle the scalar one does.

define i256 @select_i256(i256 %a, i256 %b, i64 %c) {
; CHECK-LABEL: select_i256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    beqz a0, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    ret
  %t = icmp eq i64 %c, 0
  %r = select i1 %t, i256 %a, i256 %b
  ret i256 %r
}

define i256 @select_wide_cond(i256 %a, i256 %b) {
; CHECK-LABEL: select_wide_cond:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wsltu a0, v8, v10
; CHECK-NEXT:    bnez a0, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    ret
  %t = icmp ult i256 %a, %b
  %r = select i1 %t, i256 %a, i256 %b
  ret i256 %r
}

define i256 @phi_i256(i256 %a, i256 %b, i64 %c) {
; CHECK-LABEL: phi_i256:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a0, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %else
; CHECK-NEXT:    revive.wsub v8, v8, v10
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB2_2: # %then
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    ret
entry:
  %t = icmp eq i64 %c, 0
  br i1 %t, label %then, label %else
then:
  %x = add i256 %a, %b
  br label %join
else:
  %y = sub i256 %a, %b
  br label %join
join:
  %r = phi i256 [ %x, %then ], [ %y, %else ]
  ret i256 %r
}

; Enough live wide values to force spilling, which reuses the RVV whole-register
; store and reload.
define i256 @spill_wide(ptr %p) {
; CHECK-LABEL: spill_wide:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -304
; CHECK-NEXT:    .cfi_def_cfa_offset 304
; CHECK-NEXT:    sd ra, 296(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    revive.wld v8, 0(a0)
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 264
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 232
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 200
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 168
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 136
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 104
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 72
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a1, sp, 40
; CHECK-NEXT:    vs2r.v v10, (a1) # 32-byte Folded Spill
; CHECK-NEXT:    revive.wld v10, 0(a0)
; CHECK-NEXT:    addi a0, sp, 8
; CHECK-NEXT:    vs2r.v v10, (a0) # 32-byte Folded Spill
; CHECK-NEXT:    call sink1
; CHECK-NEXT:    addi a0, sp, 264
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 232
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 200
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 168
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 136
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 104
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 72
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 40
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    addi a0, sp, 8
; CHECK-NEXT:    vl2r.v v10, (a0) # 32-byte Folded Reload
; CHECK-NEXT:    revive.wadd v8, v8, v10
; CHECK-NEXT:    ld ra, 296(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 304
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v0 = load volatile i256, ptr %p
  %v1 = load volatile i256, ptr %p
  %v2 = load volatile i256, ptr %p
  %v3 = load volatile i256, ptr %p
  %v4 = load volatile i256, ptr %p
  %v5 = load volatile i256, ptr %p
  %v6 = load volatile i256, ptr %p
  %v7 = load volatile i256, ptr %p
  %v8 = load volatile i256, ptr %p
  %v9 = load volatile i256, ptr %p
  %c = call i256 @sink1(i256 %v0)
  %a1 = add i256 %c, %v1
  %a2 = add i256 %a1, %v2
  %a3 = add i256 %a2, %v3
  %a4 = add i256 %a3, %v4
  %a5 = add i256 %a4, %v5
  %a6 = add i256 %a5, %v6
  %a7 = add i256 %a6, %v7
  %a8 = add i256 %a7, %v8
  %a9 = add i256 %a8, %v9
  ret i256 %a9
}
declare i256 @sink1(i256)
