; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+xrevivevec -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,RV64I
; RUN: llc -mtriple=riscv64 -mattr=+e,+m,+xrevivevec -target-abi lp64e \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV64E

; Wide arguments travel in the wide registers instead of by reference, so a call
; needs no marshalling at all.

declare i256 @sink2(i256, i256)
declare i256 @sink3(i256, i256, i256)
declare fastcc i256 @fast_sink(i256, i256)

define i256 @arg_passthrough(i256 %a, i256 %b) {
; CHECK-LABEL: arg_passthrough:
; CHECK:       # %bb.0:
; CHECK-NEXT:    revive.wmv w0, w1
; CHECK-NEXT:    ret
  ret i256 %b
}

define i256 @call_two(i256 %a, i256 %b) {
; RV64I-LABEL: call_two:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    .cfi_def_cfa_offset 16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    call sink2
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64E-LABEL: call_two:
; RV64E:       # %bb.0:
; RV64E-NEXT:    addi sp, sp, -8
; RV64E-NEXT:    .cfi_def_cfa_offset 8
; RV64E-NEXT:    sd ra, 0(sp) # 8-byte Folded Spill
; RV64E-NEXT:    .cfi_offset ra, -8
; RV64E-NEXT:    call sink2
; RV64E-NEXT:    ld ra, 0(sp) # 8-byte Folded Reload
; RV64E-NEXT:    .cfi_restore ra
; RV64E-NEXT:    addi sp, sp, 8
; RV64E-NEXT:    .cfi_def_cfa_offset 0
; RV64E-NEXT:    ret
  %r = call i256 @sink2(i256 %a, i256 %b)
  ret i256 %r
}

define i256 @call_three(i256 %a, i256 %b, i256 %c) {
; RV64I-LABEL: call_three:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    .cfi_def_cfa_offset 16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    call sink3
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64E-LABEL: call_three:
; RV64E:       # %bb.0:
; RV64E-NEXT:    addi sp, sp, -8
; RV64E-NEXT:    .cfi_def_cfa_offset 8
; RV64E-NEXT:    sd ra, 0(sp) # 8-byte Folded Spill
; RV64E-NEXT:    .cfi_offset ra, -8
; RV64E-NEXT:    call sink3
; RV64E-NEXT:    ld ra, 0(sp) # 8-byte Folded Reload
; RV64E-NEXT:    .cfi_restore ra
; RV64E-NEXT:    addi sp, sp, 8
; RV64E-NEXT:    .cfi_def_cfa_offset 0
; RV64E-NEXT:    ret
  %r = call i256 @sink3(i256 %a, i256 %b, i256 %c)
  ret i256 %r
}

; revive gives its internal functions fastcc, so that path matters as much.
define i256 @call_fastcc(i256 %a, i256 %b) {
; RV64I-LABEL: call_fastcc:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    .cfi_def_cfa_offset 16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    call fast_sink
; RV64I-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    addi sp, sp, 16
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64E-LABEL: call_fastcc:
; RV64E:       # %bb.0:
; RV64E-NEXT:    addi sp, sp, -8
; RV64E-NEXT:    .cfi_def_cfa_offset 8
; RV64E-NEXT:    sd ra, 0(sp) # 8-byte Folded Spill
; RV64E-NEXT:    .cfi_offset ra, -8
; RV64E-NEXT:    call fast_sink
; RV64E-NEXT:    ld ra, 0(sp) # 8-byte Folded Reload
; RV64E-NEXT:    .cfi_restore ra
; RV64E-NEXT:    addi sp, sp, 8
; RV64E-NEXT:    .cfi_def_cfa_offset 0
; RV64E-NEXT:    ret
  %r = call fastcc i256 @fast_sink(i256 %a, i256 %b)
  ret i256 %r
}

; More wide arguments than there are argument registers: the rest go on the
; stack, which must be aligned to the type.
declare i256 @sink10(i256, i256, i256, i256, i256, i256, i256, i256, i256, i256)
define i256 @call_ten(i256 %a) {
; RV64I-LABEL: call_ten:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -80
; RV64I-NEXT:    .cfi_def_cfa_offset 80
; RV64I-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    revive.wst w0, 32(sp)
; RV64I-NEXT:    revive.wst w0, 0(sp)
; RV64I-NEXT:    revive.wmv w1, w0
; RV64I-NEXT:    revive.wmv w2, w0
; RV64I-NEXT:    revive.wmv w3, w0
; RV64I-NEXT:    revive.wmv w4, w0
; RV64I-NEXT:    revive.wmv w5, w0
; RV64I-NEXT:    revive.wmv w6, w0
; RV64I-NEXT:    revive.wmv w7, w0
; RV64I-NEXT:    call sink10
; RV64I-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    addi sp, sp, 80
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64E-LABEL: call_ten:
; RV64E:       # %bb.0:
; RV64E-NEXT:    addi sp, sp, -72
; RV64E-NEXT:    .cfi_def_cfa_offset 72
; RV64E-NEXT:    sd ra, 64(sp) # 8-byte Folded Spill
; RV64E-NEXT:    .cfi_offset ra, -8
; RV64E-NEXT:    revive.wst w0, 32(sp)
; RV64E-NEXT:    revive.wst w0, 0(sp)
; RV64E-NEXT:    revive.wmv w1, w0
; RV64E-NEXT:    revive.wmv w2, w0
; RV64E-NEXT:    revive.wmv w3, w0
; RV64E-NEXT:    revive.wmv w4, w0
; RV64E-NEXT:    revive.wmv w5, w0
; RV64E-NEXT:    revive.wmv w6, w0
; RV64E-NEXT:    revive.wmv w7, w0
; RV64E-NEXT:    call sink10
; RV64E-NEXT:    ld ra, 64(sp) # 8-byte Folded Reload
; RV64E-NEXT:    .cfi_restore ra
; RV64E-NEXT:    addi sp, sp, 72
; RV64E-NEXT:    .cfi_def_cfa_offset 0
; RV64E-NEXT:    ret
  %r = call i256 @sink10(i256 %a, i256 %a, i256 %a, i256 %a, i256 %a,
                         i256 %a, i256 %a, i256 %a, i256 %a, i256 %a)
  ret i256 %r
}

; A value live across a call must survive it.
define i256 @live_across_call(i256 %a, i256 %b) {
; RV64I-LABEL: live_across_call:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -48
; RV64I-NEXT:    .cfi_def_cfa_offset 48
; RV64I-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; RV64I-NEXT:    .cfi_offset ra, -8
; RV64I-NEXT:    revive.wst w0, 8(sp) # 32-byte Folded Spill
; RV64I-NEXT:    call sink2
; RV64I-NEXT:    revive.wld w1, 8(sp) # 32-byte Folded Reload
; RV64I-NEXT:    revive.wadd w0, w0, w1
; RV64I-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; RV64I-NEXT:    .cfi_restore ra
; RV64I-NEXT:    addi sp, sp, 48
; RV64I-NEXT:    .cfi_def_cfa_offset 0
; RV64I-NEXT:    ret
;
; RV64E-LABEL: live_across_call:
; RV64E:       # %bb.0:
; RV64E-NEXT:    addi sp, sp, -40
; RV64E-NEXT:    .cfi_def_cfa_offset 40
; RV64E-NEXT:    sd ra, 32(sp) # 8-byte Folded Spill
; RV64E-NEXT:    .cfi_offset ra, -8
; RV64E-NEXT:    revive.wst w0, 0(sp) # 32-byte Folded Spill
; RV64E-NEXT:    call sink2
; RV64E-NEXT:    revive.wld w1, 0(sp) # 32-byte Folded Reload
; RV64E-NEXT:    revive.wadd w0, w0, w1
; RV64E-NEXT:    ld ra, 32(sp) # 8-byte Folded Reload
; RV64E-NEXT:    .cfi_restore ra
; RV64E-NEXT:    addi sp, sp, 40
; RV64E-NEXT:    .cfi_def_cfa_offset 0
; RV64E-NEXT:    ret
  %c = call i256 @sink2(i256 %a, i256 %b)
  %r = add i256 %c, %a
  ret i256 %r
}
